'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
test('Algolia target dry-run uses fresh isolated posts and rejects conflicting environment index', () => {
    const host = process.env.HEXO_HOST_DIR;
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'multi-algolia-test-'));
    const env = { ...process.env };
    for (const k of ['ALGOLIA_INDEX_NAME', 'ALGOLIA_APP_ID', 'ALGOLIA_API_KEY', 'ALGOLIA_SEARCH_KEY']) delete env[k];
    const write = (file, data) => { const p = path.join(root, file); fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, typeof data === 'string' ? data : JSON.stringify(data)); };
    const cli = (...args) => { const r = spawnSync(process.execPath, [path.join(host, 'node_modules/hexo/bin/hexo'), ...args], { cwd: root, env, encoding: 'utf8', timeout: 60000 }); assert.ifError(r.error); return { status: r.status, output: r.stdout + r.stderr }; };
    try {
        fs.mkdirSync(path.join(root, 'themes'));
        fs.symlinkSync(path.resolve(__dirname, '..'), path.join(root, 'themes/hexo-theme-doratiger'));
        for (const name of ['node_modules', 'package.json']) fs.symlinkSync(path.join(host, name), path.join(root, name));
        write('_config.yml', { title: 'Fixture', url: 'https://base.example.test', theme: 'hexo-theme-doratiger', language: 'en', permalink: ':title/' });
        write('_config.hexo-theme-doratiger.yml', { search: { enable: true, type: 'algolia', algolia: { app_id: 'FAKEAPP', api_key: 'PRIVATE_SENTINEL', search_key: 'SEARCH_ONLY', index_name: 'base-index', fields: ['title', 'permalink', 'content'] } }, statistics: { enable: false }, multi_deploy: { enable: true, targets: { github: { config: 'github.yml' } } } });
        write('github.yml', { site: { url: 'https://www.doratiger.top', permalink: 'overseas/:title/' }, theme: { search: { algolia: { index_name: 'overseas-index' } } } });
        write('source/_posts/fresh.md', '---\ntitle: FreshTargetArticle\ndate: 2026-09-11\n---\nFresh body documenting ERROR and FATAL logs.');
        write('source/_drafts/secret.md', '---\ntitle: DRAFT_SENTINEL\n---\nDraft');
        const result = cli('algolia', '--target', 'github', '--dry-run');
        assert.equal(result.status, 0, result.output);
        assert.match(result.output, /overseas-index/);
        assert.match(result.output, /https:\/\/www\.doratiger\.top\/overseas\/fresh\//);
        assert.doesNotMatch(result.output, /PRIVATE_SENTINEL|DRAFT_SENTINEL|base\.example\.test/);
        const firstID = result.output.match(/objectID: '([^']+)'/)[1];
        write('source/_posts/fresh.md', '---\ntitle: Renamed title\ndate: 2026-09-11\n---\nChanged body');
        const repeated = cli('algolia', '--target', 'github', '--dry-run');
        assert.equal(repeated.status, 0, repeated.output);
        assert.equal(repeated.output.match(/objectID: '([^']+)'/)[1], firstID, 'fresh databases and content edits must retain the same source identity');
        assert.equal(fs.existsSync(path.join(root, 'public')), false);
        assert.equal(fs.existsSync(path.join(root, 'db.json')), false);
        assert.equal(fs.existsSync(path.join(root, 'plugins/multi_deploy')), false);
        const allSettings = JSON.parse(fs.readFileSync(path.join(root, '_config.hexo-theme-doratiger.yml')));
        allSettings.multi_deploy.targets.cn = { config: 'cn.yml' };
        write('cn.yml', {});
        write('_config.hexo-theme-doratiger.yml', allSettings);
        const all = cli('algolia', '--all', '--dry-run', '--clean', 'false');
        assert.equal(all.status, 0, all.output);
        assert.match(all.output, /\[algolia\] target=github/);
        assert.match(all.output, /\[algolia\] target=cn/);
        assert.match(all.output, /overseas-index/);
        assert.match(all.output, /base-index/);
        assert.match(all.output, /https:\/\/www\.doratiger\.top\/overseas\/fresh\//);
        assert.match(all.output, /https:\/\/base\.example\.test\/fresh\//);
        assert.doesNotMatch(all.output, /PRIVATE_SENTINEL|DRAFT_SENTINEL/);
        assert.equal(fs.existsSync(path.join(root, 'public')), false);
        assert.equal(fs.existsSync(path.join(root, 'db.json')), false);
        assert.equal(fs.existsSync(path.join(root, 'plugins/multi_deploy')), false);
        const mixed = cli('algolia', '--all', '--target', 'github', '--dry-run');
        assert.notEqual(mixed.status, 0);
        assert.match(mixed.output, /MULTI_TARGET/);
        const positional = cli('algolia', '--all', 'github', '--dry-run');
        assert.notEqual(positional.status, 0);
        env.ALGOLIA_INDEX_NAME = 'wrong-index';
        const conflict = cli('algolia', '--target', 'github', '--dry-run');
        assert.notEqual(conflict.status, 0);
        assert.match(conflict.output, /MULTI_ALGOLIA_ENV/);
        const allConflict = cli('algolia', '--all', '--dry-run');
        assert.notEqual(allConflict.status, 0);
        assert.match(allConflict.output, /MULTI_ALGOLIA_ENV/);
        assert.doesNotMatch(allConflict.output, /\[algolia\] target=cn/);
        const unknown = cli('algolia', '--target', 'missing', '--dry-run');
        assert.notEqual(unknown.status, 0);
        delete env.ALGOLIA_INDEX_NAME;
        const built = cli('generate');
        assert.equal(built.status, 0, built.output);
        const ordinary = cli('algolia', '--dry-run');
        assert.equal(ordinary.status, 0, ordinary.output);
        assert.match(ordinary.output, /base-index/);
        assert.equal(ordinary.output.match(/objectID: '([^']+)'/)[1], firstID, 'identity is independent of target URL and permalink');
        assert.match(ordinary.output, /https:\/\/base\.example\.test\/fresh\//);
        const settings = JSON.parse(fs.readFileSync(path.join(root, '_config.hexo-theme-doratiger.yml')));
        settings.multi_deploy.targets.github.publish = { type: 'git', repo: 'git@example.test:fixture.git', branch: 'pages' };
        write('_config.hexo-theme-doratiger.yml', settings);
        write('github.yml', { site: { url: 'https://www.doratiger.top', permalink: 'overseas/:title/' }, theme: { search: { type: 'local' } } });
        const skipped = cli('algolia', '--all', '--dry-run');
        assert.equal(skipped.status, 0, skipped.output);
        assert.match(skipped.output, /Algoliasearch search function is not enabled/);
        assert.match(skipped.output, /base-index/);
        assert.doesNotMatch(skipped.output, /overseas-index/);
        const local = cli('multi-generate', 'github');
        assert.equal(local.status, 0, local.output);
        const work = path.join(root, 'plugins/multi_deploy');
        const pointer = JSON.parse(fs.readFileSync(path.join(work, 'latest/github.json')));
        const output = path.join(work, pointer.directory, 'artifact');
        const index = JSON.parse(fs.readFileSync(path.join(output, 'search.json')));
        assert.equal(index.items[0].url, 'https://www.doratiger.top/overseas/fresh/');
        assert.match(fs.readFileSync(path.join(output, 'sitemap.xml'), 'utf8'), /https:\/\/www\.doratiger\.top\/overseas\/fresh\//);
        assert.doesNotMatch(fs.readFileSync(path.join(output, 'search.json'), 'utf8'), /DRAFT_SENTINEL/);
        console.log('PASS: fresh target URLs/index, no drafts/secrets, no host output, conflicting environment and invalid target rejected.');
    } finally { fs.rmSync(root, { recursive: true, force: true }); }
});
